_core:
  default_config_hash: U05FQzBBZLLZtA9aGnomLlDDkszG50CKmrciFGUlXfM
server_url: ''
path_mapping: ''
incrementalbuild_url: ''
contentsync_url: ''
build_published: true
log_json: false
preview_entity_types: { }
preview_target: ''
preview_callback_url: ''
publish_private_files: false
log_published: false
fastbuilds_preview: false
delete_log_entities: false
log_expiration: '604800'
